blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogs/urls.py
"""Определяет схемы URL для blogs."""

from django.urls import path
from . import views


app_name = 'blogs'
urlpatterns = [
    # Домашняя страница.
    path('', views.index, name='index'),
    # Страница для создания новой записи.
    path('new_post/', views.new_post, name='new_post'),
    # Страница для редактирования записи.
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    # Страница просмотра записи.
    path('view_post/<int:post_id>/', views.view_post, name='view_post')
]

users/urls.py
"""Определяет схемы URL для пользователей."""

from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/', views.register, name='register')
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class BlogPost(models.Model):
    """Пост в блоге."""
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.title
    

class Comment(models.Model):
    """Комментарий под постом."""
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.text

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import BlogPost, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': 'Title:', 'text': 'Text'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': ''}

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import BlogPost, Comment
from .forms import PostForm, CommentForm
from django.http import Http404


def index(request):
    """Домашняя страница приложения Blog."""
    if request.method == 'POST':
        BlogPost.objects.filter(id=request.POST.get('post_id')).delete()

    posts = BlogPost.objects.order_by('-date_added')
    context = {'posts': posts, 'user': request.user}
    return render(request, 'blogs/index.html', context)


@login_required
def new_post(request):
    """Определяет новую запись."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = PostForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('blogs:view_post', new_post.id)
    
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)


@login_required
def edit_post(request, post_id):
    """Редактирование записи."""
    post = BlogPost.objects.get(id=post_id)
    check_post_owner(request, post)
    
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = PostForm(instance=post)
    else:
        # Отправка данных POST; обработать данные.
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:view_post', post.id)
    
    context = {'post': post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)


def check_post_owner(request, post: BlogPost):
    """Проверка того, что запись принадлежит текущему пользователю."""
    if post.owner != request.user:
        raise Http404
    

def view_post(request, post_id):
    """Просмотр записи."""
    post = BlogPost.objects.get(id=post_id)
    form = CommentForm()    # Это строка нужна была чтобы передать форму в render()
    if request.method != 'POST':
        # Данные не отправлялись.
        pass
    else:
        # Данные для создания нового комментария были переданы.
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.owner = request.user
            new_comment.post = post
            new_comment.save()
            return redirect('blogs:view_post', post.id)

    comments = Comment.objects.filter(post=post).order_by('-date_added')
    context = {'post': post, 'comments': comments}
    return render(request, 'blogs/view_post.html', context)
    
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Вход пользователя, и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('blogs:index')
    
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}
{% load static %}


<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width initial-scalse=1 shrink-to-fit=no">
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
        <title>Blog</title>

        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <a class="navbar-brand" href="{% url 'blogs:index' %}">Blog</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text">Hello, {{ user.username }}.</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>
    </body>
</html>

blogs/templates/blogs/edit_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}


{% block page_header %}
    <h2>Edit the post</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'blogs:edit_post' post.id %}" method='post' class="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button class="btn btn-lg btn-primary" name='submit'>Save changes</button>
        {% endbuttons %}
    </form>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}


{% block page_header %}
<div class="jumbotron">
    <h2 class="display-3">Follow your blog.</h2>

    <p class="lead">With Blog you can folow your blog, folowing other blogs and comment it.</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
</div>
{% endblock page_header %}

{% block content %}
{% if user.is_authenticated %}
<a class="btn btn-primary mb-2" href="{% url 'blogs:new_post' %}" role="button">Add a new post</a>
{% endif %}

{% for post in posts %}
<div class="card mb-2">
    <div class="card-body">
        <h4 class="card-title">{{ post.title }}</h4>
        <h6 class="card-subtitle mb-2 text-muted">{{ post.owner.username }}</h6>
        <p class="card-text">{{ post.text }}</p>
        <p class="card-subtitle mb-2 text-muted">{{ post.date_added|date:'M d, Y H:i' }}</p>
        <div class="btn-group" role="group" aria-label="Post actions">
            {% if post.owner == user %}
            <a class="btn btn-primary" href="{% url 'blogs:edit_post' post.id %}" role="button">Edit post</a>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deletePost{{ post.id }}">
                Delete
            </button>
            {% endif %}
            <a class="btn btn-primary" href="{% url 'blogs:view_post' post.id %}">Comments</a>
        </div>
        <div class="modal" id="deletePost{{ post.id }}" tabindex="-1" role="dialog"
            aria-labelledby="deletePostLabel{{ post.id }}" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deletePostLabel{{ post.id }}">
                            Are you sure you want to delete this post?
                        </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close{{ topic.id }}">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <form action="{% url 'blogs:index' %}" method="post" class="form">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete</button>
                            <input type="hidden" name="post_id" value="{{ post.id }}">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% empty %}
<p>There are no any posts added yet.</p>
{% endfor %}
{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}


{% block page_header %}
    <h2>Add a new post</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'blogs:new_post' %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-lg btn-primary" name='submit'>Add post</button>
        {% endbuttons %}
    </form>
{% endblock content %}

blogs/templates/blogs/view_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}


{% block page_header %}
<h2>Post</h2>
{% endblock page_header %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">{{ post.title }}</h4>
        <h6 class="card-subtitle mb-2 text-muted">{{ post.owner.username }}</h6>
        <p class="card-text">{{ post.text }}</p>
        <p class="card-subtitle mb-2 text-muted">{{ post.date_added|date:'M d, Y H:i' }}</p>
        <div class="btn-group" role="group" aria-label="Post actions">
            {% if post.owner == user %}
            <a class="btn btn-primary" href="{% url 'blogs:edit_post' post.id %}" role="button">Edit post</a>
            {% endif %}
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#comments{{ post.id }}"
                aria-expanded="false" aria-controls="comments">
                Comments
            </button>
        </div>
        <div class="collapse" id="comments{{ post.id }}">
            <div class="card mt-2">
                <div class="card-body">
                    {% if user.is_authenticated %}
                    <button class="btn btn-primary mb-2" type="button" data-toggle="modal"
                        data-target="#addComment{{ post.id }}">
                        Add comment
                    </button>
                    {% endif %}

                    <div class="modal" id="addComment{{ post.id }}" tabindex="-1" role="dialog"
                        aria-labelledby="addComment{{ post.id }}Label" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="addComment{{ post.id }}Label">Add comment</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        &times;
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form action="{% url 'blogs:view_post' post.id %}" method="post" class="form">
                                        {% csrf_token %}
                                        {#{% bootstrap_form form %}#}
                                        {#{% buttons %}#}
                                        {#<button class="btn btn-primary" name="submit">Add comment</button>#}
                                        {#{% endbuttons %}#}
                                        {#<input name="post_id" type="hidden" value="{{ post.id }}">#}
                                        <div class="input-group">
                                            <input type="text" class="form-control" name="text">
                                            <input name="post" type="hidden" value="{{ post }}">
                                            <div class="input-group-append">
                                                <button class="btn btn-primary" type="submit">Add
                                                    comment</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% for comment in comments %}
                    <div class="card mb-2">
                        <div class="card-body">
                            <div class="media">
                                {#<img class="d-flex align-self-start mr-3" scr="" alt="{{ user.username }} avatar">#}
                                <div class="media-body">
                                    <h5>{{ comment.owner.username }}</h5>
                                    <p>{{ comment }}</p>
                                    <p class="text-muted">{{ comment.date_added }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <p>There are no any comments added yet.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}